version: '3.8'

services:
  server: 
    image: express-app
    depends_on:
      - mongo
      - redis
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    ports: 
      - 3000:3000
    volumes: 
      - ./:/usr/src/app
    environment: 
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database

  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  redis:
    image: redis:6.2-alpine
    ports: 
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes'] # Overwrite the CMD
    volumes: 
      - ./redis_data:/data
